name: "ORNL Datasets"
title: "ORNL Dataset Portal"
author: "Oak Ridge National Laboratory"
description: "A collaborative space for the HPC and Data Science communities."
baseurl: "/ornl-datasets"
url: "https://frobnitzem.github.io/ornl-datasets"
repo_url: "https://github.com/frobnitzem/ornl-datasets"
show_excerpts: true

github_username: ornl

# Build settings
theme: minima
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: "/news/:year/:month/:day/:title/"
  datasets:
    output: true
    permalink: "/:collection/:categories/:name"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - Gemfile
   - Gemfile.lock
   - README.md
   - run.sh
   - TODO
